### PR TITLE
feat: use Konva object pass through from ImageConfig param

### PR DESCRIPTION
**Pull request by zthomas**
## Summary
Allow Pikaso to use an `Image` instance passed in through `Konva.ImageConfig`. This is mainly used to give the user more control of the Image instances that they can pass in. Right now Pikaso's [ImageDrawer insert function](https://github.com/pikasojs/pikaso/blob/master/src/shape/drawers/ImageDrawer/index.ts#L35) createa its own Konva Image object. This makes it impossible for users to add videos to the canvas. 

The original Konva API allows you to pass in image object that can also be a HTML video element to support adding video to canvas. The changes basically passes that ability through.

### CODE REVIEW

**Comment by raminious** [comment]
@zthomas  Thanks for creating this pull request. It totally makes sense and I'm with you to add the feature to [ImageDrawer insert function](https://github.com/pikasojs/pikaso/blob/master/src/shape/drawers/ImageDrawer/index.ts#L35)  

However I'm not okay with the implementation for two essential reasons: 
1- I'm against of using `as` in TS if it's possible   
2- You have to pass an empty string for the first argument `editor.shapes.image.insert('', { image: <Object>})` and like to keep the api simple as much as possible   

So I made some minor changes in your pull request. with this changes the first parameter will accept a `File` or `Konva.Image` or a `string` and the second one will remain optional.   

Also I added three more unit tests.

Please check my commit and let me know if that looks good to you and then I'll merge that.

Cheers.

**Comment by zthomas** [comment]
Thanks. I actually tried a similar approach on my first attempt. It also overloaded the first parameter to accept a `Konva.Image`however it didn't actually work for me in practice. I doubled checked that I was passing the Konva.Image instance from my application but it didn't pass the check in that function. I suspect the reason might be becuase we are using different constructors (possibly different versions of Konva). 


The `instanceof` checks might not be that robust when in a library context. If there was a way to do duct typing check or something that might be more robust. 

I'll run this new update against my codebase and see if it has the same issues.

**Comment by raminious** [comment]
> Thanks. I actually tried a similar approach on my first attempt. It also overloaded the first parameter to accept a `Konva.Image`however it didn't actually work for me in practice. I doubled checked that I was passing the Konva.Image instance from my application but it didn't pass the check in that function. I suspect the reason might be becuase we are using different constructors (possibly different versions of Konva).
> 
> The `instanceof` checks might not be that robust when in a library context. If there was a way to do duct typing check or something that might be more robust.
> 
> I'll run this new update against my codebase and see if it has the same issues.

please check here  
https://github.com/pikasojs/pikaso/pull/11/files#diff-1f8f48101abb7d8a5547374efdf6e0069559d969a5db10fd068df000472aa048R29

**Comment by zthomas** [comment]
Yup, I saw that unit test earlier. It will pass the unit test because the way that it's set up it'll be using the same Konva library in the test runner as the library. I just have to check that in my application that it still works. I might be using a different version of Konva depending on how the dependencies are setup.

**Comment by raminious** [comment]
> Yup, I saw that unit test earlier. It will pass the unit test because the way that it's set up it'll be using the same Konva library in the test runner as the library. I just have to check that in my application that it still works. I might be using a different version of Konva depending on how the dependencies are setup.

@zthomas basically it's better to import Konva from Pikaso  

```import { Konva } from 'pikaso'``` 
or install equal major version of Konva independently for the sake of consistency

**Review by raminious — APPROVED** [review]

**Pull request merged**
